config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "rooms#index"
# トップページにアクセスした時roomsコントローラーのindexアクションのビューが表示される
# ログインしているユーザーが参加しているチャットルーム名とログインしているユーザー名を持っているサイドバーが表示される

  resources :users, only: [:edit, :update]
# ユーザーの情報を編集するページを表示するためにonlyオプションでeditアクションを指定しました
# ユーザーの情報を編集して更新ができるようにonlyオプションでupdateアクションを指定しました

  resources :rooms, only: [:new, :create, :destroy] do
# チャットルームの新規作成ページとチャットルームが作成できれば良いのでonlyオプションでnewアクションとcreateアクションを指定している
# チャットルームの終了はルームを削除することで実現させたいのでroomsコントローラーにdestroyアクションを追加している
     resources :messages, only: [:index, :create]
  end
# メッセージを投稿するときはどのチャットルームから投稿されたものなのかをパスから判断したいのでroomsコントローラーにmessagesコントローラーをネストさせる必要がある
# 投稿されたメッセージの一覧を確認するためにはどのチャットルームなのか判断できるようにするためにindexアクションを指定している
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
# roomモデルは複数のメッセージを持つことができる
# userモデルは複数のメッセージを持つことができる
# それぞれのモデルとmessageモデルは一体多の関係になるのでbelongs_toメソッドを使ってroomモデルとuserモデルの関係を表している

  has_one_attached :image
# messagesテーブルとactive storageのテーブルで管理されている画像ファイルのアソシエーションを記述している(attachは貼り付けるという意味)

  validates :content, presence: true, unless: :was_attached?
# unlessオプションをつけることで指定したメソッドの処理がfalseであればcontentカラムが空ではないかを検証する
# 画像が添付されていればメッセージが空でもバリデーションに引っ掛からず画像のみを投稿することができる

  def was_attached?
    self.image.attached?
# 投稿するときに画像が添付されているかを確認している
# 添付されていればtrue されていなければfalseを返す
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
# roomsテーブルのレコードが削除されたときはそのテーブルのカラムの外部キーを持っている中間テーブルのレコードも削除する必要があるのでdependentオプションでdestroyメソッドをつけている
  has_many :users, through: :room_users
# roomsテーブルと中間テーブルは一対多の関係になるのでhas_manyオプションで中間テーブルを指定している
# usersテーブルは多対多の関係であるためhas_manyオプションでusersテーブルを指定している
# 多対多の関係になったときは間に中間テーブルを置く必要があるのでthroughオプションで中間テーブルを指定している
  has_many :messages, dependent: :destroy
# roomモデルは複数のメッセージを持つことができるのでhas_manyオプションでmessageモデルを指定している
# roomsテーブルのレコードが削除されたときはそのテーブルのカラムの外部キーを持っているmessagesテーブルのレコードも削除する必要があるのでdependentオプションでdestroyメソッドをつけている
  validates :name, presence: true
# チャットルーム名を空にしたままチャットルームを作成しようとするとエラーが起きる
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
# 参照先のテーブルと中間テーブルは一対多の関係性になるためbelongs_toメソッドを使って参照先テーブルを指定している
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
# usersテーブルと中間テーブルは一対多の関係になるのでhas_manyメソッドで中間テーブルを指定している
# 多対多の関係にあるテーブルの間には中間テーブルを置く必要があるのでthroughオプションで中間テーブルを指定している

  has_many :messages
# ユーザーは複数のメッセージを持つことができるのでhas_manyオプションでmessageモデルを指定している

  validates :name, presence: true
# 名前を空にして新規登録やログインが出来ないようにした
# presenceは存在するという意味
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
# コントローラーのアクションが呼び出された時にログインをしていなければユーザーをログイン画面に遷移させる
# application_controller.rbに記述することで全てのコントローラーに処理を読み込ませることができる

  before_action :configure_permitted_parameters, if: :devise_controller?
# deviseの処理が行われる場合はconfigure_permitted_parametersメソッドが呼び出される

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
# deviseからparamsという名のdevise_parameter_sanitizerがコントローラーに送られてくる
# 新規登録の場合はnameキーのバリューをDBに保存できるようにしている
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end
# メッセージを投稿するためにmessageモデルの新規のインスタンスを生成してform_withのmodelオプションで使えるようにした
# チャットルーム名をクリックするとメッセージ一覧(messagesコントローラーのindexアクションのビュー)が確認できる
# そのアクションに遷移するときにmessagesコントローラーのindexアクションにroom_idキーが入ったparamsが届けられる
# そのキーのバリューを取得するとroomsテーブルのレコードが取得できる
# form_withの引数にmessageモデルの新規のインスタンスが入った@messageとルームのidが入った@roomを置くことで自動的に入力した内容がmessagesコントローラーのcreateアクションに送信される
# チャットルームに紐づいたメッセージを全て取得できる メッセージ一覧で投稿者名を表示するためDBへのアクセス回数が増えるのでincludesメソッドの引数にuserモデルを指定している


  def create
    @room = Room.find(params[:room_id])
# 投稿フォームからルームのidが送られてくるのでそれを受け取るためにparams[:room_id]としている
# チャットルームのレコードを取得することができる
    @message = @room.messages.new(message_params)
# messages.newと複数形にすることで@roomに紐づいたmessageモデルのインスタンスを生成できる
# messagesコントローラーはroomコントローラーにネストされているのでmessageモデルのインスタンスを生成するときは紐づいているroomモデルのレコードが必要である
    if @message.save
      redirect_to room_messages_path(@room)
# メッセージの保存に成功した場合はメッセージ一覧に遷移させる
    else
      @messages = @room.messages.includes(:user)
      render :index
# メッセージの保存に失敗した場合は今まで投稿されたメッセージを表示した上でメッセージ一覧に戻すためチャットルームに紐づく今まで投稿されたメッセージを全て取得している
# 入力された内容を残したままメッセージ一覧に遷移させる
# indexアクションで@messages = @room.messages.includes(:user)を定義したのでelseの処理に記述しないとエラーが出る
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
# paramsで送られてくるcontentキーとimageキーのバリューの保存を許可している
# メッセージを投稿できるのはログインしているユーザーなのでmessagesテーブルの誰が投稿したかを示すuser_idカラムにログインしているユーザーのidを保存している
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end
  

  def new
    @room = Room.new
  end
# new.html.erbのform_withメソッド内で新規のroomモデルのインスタンスを使用することで入力した内容がroomsコントローラーのcreateアクションに自動的に送信してくれる

  def create
    @room = Room.new(room_params)
# roomモデルの新規インスタンスをroom_paramsの内容を持って生成している
    if @room.save
      redirect_to root_path   
# インスタンスの保存に成功した場合はトップページに遷移させる
    else
      render :new
# インスタンスの保存に失敗した場合は入力した内容が残ったままチャットルーム作成ページに遷移させる
    end
  end

  def destroy
    room = Room.find(params[:id])
# ルームを削除するときにビューからルームのidが渡されるのでそれを受け取るためにparams[:id]としている
# 削除したいルームのレコードを取得できる
    room.destroy
    redirect_to root_path
# ルームを削除したときはサイドバーしか表示されないビューにリダイレクトされる
  end

  private
  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
# チャットルームを作成したときにビューからparams(ハッシュ)が送られてくる
# そのハッシュからまずroomキーを取り出す必要がある nameキーの値の保存を許可している
# user_idsのバリューは配列であるため配列を受け取るために空の配列を用意している
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end
# views/users/edit.html.erbファイルを閲覧できるようにusersコントローラーにeditアクションを定義しました

  def update
    if current_user.update(user_params)
# ログインしているユーザーの情報をuser_paramsの内容を持って更新している
      redirect_to root_path 
# ログインしているユーザーの情報の更新に成功した場合は更新された情報を持ったトップページが表示される 
    else
      render :edit
# ログインしているユーザーの情報の更新に失敗した場合は入力された情報が残ったままusers/edit.html.erbに遷移させる
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
# 編集ページからusersコントローラーにparamsが送られてくる
# そのハッシュの中にuserというキーがあるのでrequireメソッドを使ってuserキーを取り出している
# nameカラムとemailカラムを保存できるようにしている

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp100</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%# href属性を使ってCSSとして指定したURLを表示させる %>
    <%# そのURLの種類がCSSに関係するstylesheetであるためrel属性でstylesheetを指定している %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class = "chat-header">
<%# チャットのルーム名とチャットを終了するボタンが表示されている箱である %>
  <div class = "left-header">
<%# チャットルーム名を示す箱である %>
    <%= @room.name %>
<%# チャットルーム名をクリックするとチャットルームで投稿されたメッセージ一覧が表示される %>
<%# その際にビューからmessagesコントローラーのindexアクションにチャットルームのidが入ったparamsが届くのでそれを受け取るためにparams[:room_id]としている %>
<%# @room = Room.find(params[:room_id])とすることでチャットルームのレコードを取得できる %>
<%# その変数にカラム名をつけるとカラムの内容が表示される %>
  </div>
  <div class = "right-header">
<%# チャット終了ボタンの箱である %>
    <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
<%# @roomにはチャットルームのレコードが入っている %>
<%# ルームを削除するにはパスにルームのidを渡す必要があるので引数に@roomを入れている %>
<%# HTTPメソッドがget以外のなので記述している %>
  </div>
</div>

<div class = "messages">
  <%= render partial: "message", collection: @messages %>
<%# メッセージ内容を管理するための_message.html.erbを呼び出している %>
<%# @messagesにはチャットルームに紐づくmessagesテーブルのレコード全てが入っている %>
<%# そのレコードの数だけ_message.html.erbが展開される %>
<%# _message.html.erb内で@messagesのレコード1つをmessageという変数で扱うことができる %>
</div>


<%= form_with model: [@room, @message], class: "form", local: true do |f| %>
<%# 入力欄と画像添付ボタンと送信ボタンを持つ箱である %>
  <div class = "form-input">
<%# 入力欄と画像を添付ボタンを持つ箱である %>
    <%= f.text_field :content, class: "form-message", placeholder: "入力する" %>
    <label class = "form-image">
      <div class = "image-file">画像</div>
      <%= f.file_field :image, class: "hidden" %>
    </label>
  </div>
  <%= f.submit "送信", class: "form-submit" %>
<% end %>

app/views/messages/_message.html.erb
<%# messageはmessagesテーブルのレコード一つを表す %>
  <div class = "message">
<%# 投稿者 投稿時間 投稿内容を持つ箱である %>
    <div class = "message_name_with_message_date">
<%# 投稿者名と投稿時間を持つ箱である %>
      <div class = "message-user">
<%# 投稿者名を持つ箱である %>
        <%= message.user.name %>
      </div>

      <div class = "message-date">
<%# 投稿時間を持つ箱である %>
        <%= l message.created_at %>
<%# lメソッドを使うと指定した現地時間に対応した時間を表すことができる %>
      </div>
    </div>

    <div class = "message-content">
<%# 投稿内容を持つ箱である %>
       <%= message.content %>
    </div>

    <%= image_tag message.image.variant(resize: "500 x 500"), class: "message-image" if message.image.attached? %>
<%# image_tagメソッドを使うことで画像を表示できる %>
<%# messageモデルにimageカラムとのアソシエーションを記述したので messagesテーブルに紐づく画像を表示することができる %>
<%# if message.image.attached?という記述が無いと投稿されたメッセージに画像を添付していない時でも画像を表示させる記述を読み込んでしまいエラーが起きるのでその記述は必要である %>
<%# 投稿したメッセージに画像が添付されている場合は画像が表示される 画像が添付されていない場合はimage_tag message.imageの記述は読み込まれず画像が表示されない %>
<%# 表示される画像に対してvariantメソッド(異なったという意味)を使うことでサイズを調整することができる %>
<%# resize(大きさを変更するという意味)オプションを使うことで任意のサイズに調整することができる %>
  </div>



  
  

app/views/messages/_side_bar.html.erb
<div class = "side-bar-header">
<%# ログインしているユーザー名とチャットを作成するボタンが表示されている箱である %>
  <div class = "header-name">
<%# ログインしているユーザー名を表示する箱である %>
    <%= link_to current_user.name, edit_user_path(current_user.id)%>
<%# リンクとなる文字列がログインしているユーザーの名前になる %>
<%# リンク先がユーザー編集ページとしたいのでusersコントローラーのeditアクションのパスを指定している %>
<%# そのパスにはどのユーザーの情報を編集したいかの情報を含める必要があるのでログインしているユーザーのidを入れている %>
  </div>
  <div class = "create-room">
<%# チャットルームを作成するボタンの箱である %>
    <%= link_to "チャットを作成するよ!!", new_room_path %>
<%# リンク先がチャットルームの新規作成画面である %>
  </div>
</div>

<div class = "rooms">
<%# ログインしているユーザーが参加しているチャットルーム名が表示されている箱である %>
   <% current_user.rooms.each do |room| %>
<%# ログインしているユーザーが所属しているroomsテーブルのレコードを全て取得している %>
<%# そのレコードが一つ一つroomに格納される %>
     <div class = "room-name">
       <%= link_to room.name, room_messages_path(room.id) %>
<%# ログインしているユーザーが所属しているチャットルーム名がリンクとなる %>
<%# チャットルームのメッセージ一覧の画面に遷移することができる %>
<%# その画面に遷移するためにはどのルームのメッセージ一覧なのかが重要になるためルームのidをパスにつける必要がある %>
     </div>
   <% end %>
</div>

app/views/messages/index.html.erb
<div class = "wrapper">
<%# サイドバーとチャット画面を持つ箱である %>
 <div class = "side-bar">
<%# サイドバーを持つ箱である %>
  <%= render partial: "side_bar" %>
 </div>
 <div class = "chat">
<%# チャット画面を持つ箱である %>
  <%= render partial: "main_chat" %>
 </div>
</div>


<%# メッセージ一覧を確認できるビューファイルにサイドバーとチャット画面のerbファイルを読み込めるように設定した %>
<%#  %>

app/views/rooms/index.html.erb
<div class = "wrapper">
  <div class = "side-bar">
    <%= render partial: "messages/side_bar" %>
  </div>
</div>
<%# サイドバーのみが表示される %>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
<%# modelオプションでroomモデルの新規インスタンスが入ったインスタンス変数を指定すると入力された内容がroomsコントローラーのcreateアクションに送信される %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name = "room[user_ids][]">
          <option value = "">チャットするユーザーを選択してください</option>
<%# option要素のvalue属性に空の値を指定することで空の値がコントローラーに送信される %>
          <% User.where.not(id: current_user.id).each do |user| %>
<%# usersテーブルからidがログインしているユーザーのid以外のレコードを全て取得している %>
<%# ログインしているユーザーはチャットルームのメンバーに含まれているのでプルダウンの選択肢に表示させる必要がないためそのユーザーを除外しました %>
<%# usersテーブルのレコードの数だけdo ~ endが繰り返される %>
            <option value = <%= user.id %>><%= user.name %></option>
<%# プルダウンで選択した人のidがroom[user_ids][]の空の配列に入る %>
<%# {"room" => {"user_ids(チャットルームに所属させるユーザーのidを示す)" => [プルダウンで選択した人のid]}} がコントローラーに送られる %>
          <% end %>
        </select>
        <input name = "room[user_ids][]" type = "hidden" value = <%= current_user.id %>>
<%# input要素で入力フォームを作ることができログインしているユーザーのidが既に入力されている %>
<%# ログインしているユーザーをroom[user_ids][]の空の配列に入れることができる %>
<%# name属性を使っているのでログインしているユーザーのidをコントローラーに送ることができる %>
<%# 最終的にコントローラーに送られるparamsの中身は以下のようになる %>
<%# {"room" => {"user_ids" => [プルダウンで選択した人のid, ログインしているユーザーのid]}}がコントローラーに送られる %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
<%# ログアウトというボタンをクリックするとログアウトができるようにしたいのでdevise/sessionsコントローラーのdestroyアクションのパスであるdestroy_user_session_pathをリンク先として指定している %>
<%# HTTPメソッドはDELETEなのでそれを記述する必要がある %>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>